import * as fs from "fs";
import * as path from "path";

export interface SecurityException {
  id: string;
  target: "npm" | "cargo" | "docker" | "terraform";
  package?: string;
  resource?: string;
  severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  owner: string;
  reason: string;
  created_at?: string;
  expires_at: string;
  status: "active" | "resolved" | "expired";
}

export interface SecurityExceptionsFile {
  version: string;
  description?: string;
  exceptions: SecurityException[];
}

export function validateSecurityExceptions(
  filePath: string,
  now: Date = new Date()
): { valid: boolean; errors: string[]; activeExceptions: SecurityException[] } {
  const errors: string[] = [];
  const activeExceptions: SecurityException[] = [];

  if (!fs.existsSync(filePath)) {
    errors.push(`Security exceptions file not found: ${filePath}`);
    return { valid: false, errors, activeExceptions };
  }

  let data: SecurityExceptionsFile;
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    data = JSON.parse(raw) as SecurityExceptionsFile;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    errors.push(`Invalid JSON syntax in ${filePath}: ${message}`);
    return { valid: false, errors, activeExceptions };
  }

  if (!Array.isArray(data.exceptions)) {
    errors.push(`"exceptions" property must be an array.`);
    return { valid: false, errors, activeExceptions };
  }

  const validTargets = new Set(["npm", "cargo", "docker", "terraform"]);
  const validStatuses = new Set(["active", "resolved", "expired"]);

  data.exceptions.forEach((exc, index) => {
    const prefix = `Exception #${index + 1} (${exc.id || "UNKNOWN_ID"})`;

    if (!exc.id || typeof exc.id !== "string" || exc.id.trim() === "") {
      errors.push(`${prefix}: Missing or invalid "id".`);
    }

    if (!exc.target || !validTargets.has(exc.target)) {
      errors.push(
        `${prefix}: Invalid "target" '${exc.target}'. Allowed: npm, cargo, docker, terraform.`
      );
    }

    if (!exc.owner || typeof exc.owner !== "string" || exc.owner.trim() === "") {
      errors.push(
        `${prefix}: Missing "owner". Every exception must have a designated owner (e.g. security@lumigift.com or @handle).`
      );
    }

    if (!exc.reason || typeof exc.reason !== "string" || exc.reason.trim().length < 10) {
      errors.push(
        `${prefix}: Missing or insufficient "reason". Must provide a clear justification (minimum 10 characters).`
      );
    }

    if (!exc.status || !validStatuses.has(exc.status)) {
      errors.push(
        `${prefix}: Invalid "status" '${exc.status}'. Allowed: active, resolved, expired.`
      );
    }

    if (!exc.expires_at) {
      errors.push(
        `${prefix}: Missing "expires_at". Every exception must define an explicit expiry date.`
      );
    } else {
      const expiryDate = new Date(exc.expires_at);
      if (isNaN(expiryDate.getTime())) {
        errors.push(
          `${prefix}: "expires_at" is not a valid ISO 8601 date string (${exc.expires_at}).`
        );
      } else if (exc.status === "active") {
        if (expiryDate.getTime() <= now.getTime()) {
          errors.push(
            `❌ EXPIRED EXCEPTION: ${prefix} expired on ${expiryDate.toISOString()}. Owner: ${exc.owner}. You must fix the vulnerability or renew the exception.`
          );
        } else {
          activeExceptions.push(exc);
        }
      }
    }
  });

  return {
    valid: errors.length === 0,
    errors,
    activeExceptions,
  };
}

export function syncToolingIgnoreFiles(
  activeExceptions: SecurityException[],
  rootDir: string = process.cwd()
): void {
  // Generate .trivyignore for Docker / Terraform / FS scans
  const trivyIgnorePath = path.join(rootDir, ".trivyignore");
  const trivyLines = [
    "# Automatically generated by validate-security-exceptions.ts",
    "# Do not edit directly; add approved exceptions to .security-exceptions.json",
    "",
  ];

  for (const exc of activeExceptions) {
    trivyLines.push(
      `# Target: ${exc.target} | Owner: ${exc.owner} | Expires: ${exc.expires_at}`
    );
    trivyLines.push(`# Reason: ${exc.reason}`);
    trivyLines.push(exc.id);
    trivyLines.push("");
  }

  fs.writeFileSync(trivyIgnorePath, trivyLines.join("\n"), "utf-8");
}

// Direct CLI execution
if (require.main === module) {
  const rootDir = process.cwd();
  const exceptionsFile = path.join(rootDir, ".security-exceptions.json");

  console.log("=======================================================");
  console.log("   Lumigift Security Exceptions Validator");
  console.log("=======================================================");
  console.log(`Checking exceptions in: ${exceptionsFile}`);
  console.log(`Current Time (UTC):     ${new Date().toISOString()}\n`);

  const result = validateSecurityExceptions(exceptionsFile);

  if (!result.valid) {
    console.error("❌ Validation Failed:");
    for (const err of result.errors) {
      console.error(`   - ${err}`);
    }
    console.error(
      "\n🚫 All security exceptions must have a valid owner, clear reason, and a future expiration date."
    );
    process.exit(1);
  }

  console.log(`✅ All ${result.activeExceptions.length} active exceptions are valid and unexpired:`);
  for (const exc of result.activeExceptions) {
    console.log(
      `   • [${exc.target.toUpperCase()}] ${exc.id} (Owner: ${exc.owner}, Expires: ${exc.expires_at})`
    );
  }

  // Generate / update .trivyignore
  syncToolingIgnoreFiles(result.activeExceptions, rootDir);
  console.log("\n✅ Synchronized active exceptions with tooling ignore files (.trivyignore).");
}
